name: Packages build and publish to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NUGET_REPO_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v2

    - name: ⚙️ Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 🧹 Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: 🔁 Restore packages
      run: dotnet restore

    - name: 🛠️ Building in release mode
      run: dotnet build --configuration Release --no-restore

    - name: 🧪 Test
      run: dotnet test --no-restore --verbosity normal

    - name: 🗳️ Creating library package for release
      run: dotnet pack -c Release --no-restore -p:PublicRelease=true

    - name: 📦 Push packages to NuGet
      run: dotnet nuget push '**/bin/**/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_REPO_URL }} --skip-duplicate --no-symbols